
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('date.format.short','dd/MM/yyyy',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('date.format.long','dd/MM/yyyy HH:mm',0);

INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('job.enabled','TRUE',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('job.delay.min','3',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('job.tries','20',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('job.keep.day','30',0);

INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.enabled','FALSE',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.serverHost','smtp.gmail.com',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.serverPort','465',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.username','xxxx@gmail.com',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.password','yyyyy',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.enableSsl','TRUE',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.auth','TRUE',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.domainName','',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.enableTls','FALSE',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.requireTls','FALSE',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.delay.min','3',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.tries','10',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.keep.day','30',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('mail.sender','XXXX <xxxx@gmail.com>',0);

INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('import.path','.',0);
INSERT INTO CONFIGURATIONS (NAME,VALUE,VERSION) VALUES('responsabile.uo','John Doe',0);
