INSERT INTO GENERE_ASSET(ID,DESCRIZIONE,TIPO) VALUES (1, 'TOMTOM', 3);
INSERT INTO GENERE_ASSET(ID,DESCRIZIONE,TIPO) VALUES (2, 'VIACARD', 3);
INSERT INTO GENERE_ASSET(ID,DESCRIZIONE,TIPO) VALUES (3, 'TELEPASS', 3);

INSERT INTO GENERE_ASSET(ID,DESCRIZIONE,TIPO) VALUES (4, 'TOMTOM', 2);
INSERT INTO GENERE_ASSET(ID,DESCRIZIONE,TIPO) VALUES (5, 'VIACARD', 2);
INSERT INTO GENERE_ASSET(ID,DESCRIZIONE,TIPO) VALUES (6, 'TELEPASS', 2);