INSERT INTO PERMISSIONS VALUES (1, '*', 0);
INSERT INTO PERMISSIONS VALUES (2, 'VIEW.ALL', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.REPORT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.REPORT.*', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.REPORT.SCADENZE', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.REPORT.MEZZI', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.REPORT.POSTAZIONI', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.REPORT.CONSUMI', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.MEZZI', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.MEZZI.*', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.MEZZI.TIPOMEZZO', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.MEZZI.ASSICURAZIONE', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.MEZZI.POLIZZA', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.MEZZI.MEZZO', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.MEZZI.SOCCORSI', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.RIFORNIMENTI', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.RIFORNIMENTI.*', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.RIFORNIMENTI.PIN', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.RIFORNIMENTI.CARTE', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.RIFORNIMENTI.RIFORNIMENTI', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.RIFORNIMENTI.SCONTRINI', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.RIFORNIMENTI.CARBURANTI', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.RIFORNIMENTI.ANOMALIE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.ANAGRAFICA', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.ANAGRAFICA.*', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.ANAGRAFICA.PROVINCE', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.ANAGRAFICA.AREE', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.ANAGRAFICA.POSTAZIONI', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.ANAGRAFICA.PERSONE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.*', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.USERGROUP', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.USERGROUP.*', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.USERGROUP.USER', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.USERGROUP.GROUP', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.USERGROUP.PERMISSION', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.USERGROUP.EVENT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.CONFIG', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.MANAGE', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.JOB', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.MAIL', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.INFO', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.IMPORT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MENU.SYSTEM.GENERI', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.JOB.NEW', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('DASHBOARD.VIEW', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.*', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.ID.VIEW', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.DESCRIZIONE.VIEW', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.DESCRIZIONE.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.SERBATOIO.VIEW', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.SERBATOIO.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.CONSUMO_URBANO.VIEW', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.CONSUMO_URBANO.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.CONSUMO_EXTRAURBANO.VIEW', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.CONSUMO_EXTRAURBANO.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.TIPO_CARBURANTE.VIEW', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.TIPOMEZZO.TIPO_CARBURANTE.EDIT', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.TIPOMEZZO.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.TIPOMEZZO.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSICURAZIONE.*', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSICURAZIONE.ID.VIEW', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSICURAZIONE.NOME.VIEW', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSICURAZIONE.NOME.EDIT', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.ASSICURAZIONE.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.ASSICURAZIONE.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.NUMERO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.NUMERO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.MEZZO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.MEZZO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.ASSICURAZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.ASSICURAZIONE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.DECORRENZA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.DECORRENZA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.SCADENZA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POLIZZA.SCADENZA.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.POLIZZA.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.POLIZZA.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.TARGA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.TARGA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.CODICE_RADIO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.CODICE_RADIO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.NOTE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.NOTE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.TIPO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.TIPO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.SCADENZA_REVISIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.SCADENZA_REVISIONE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.SCADENZA_BOLLO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.SCADENZA_BOLLO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.STATO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.STATO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.DATA_STATO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.DATA_STATO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.NOTE_STATO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.NOTE_STATO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.UTENTE_STATO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.UTENTE_STATO.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.RIFORNIMENTI.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.POLIZZE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.CARTE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.STATI.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.SOCCORSI.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.ASSEGNAZIONI.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.MEZZO.DOTAZIONI.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.MEZZO.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.MEZZO.DELETE', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.MEZZO.ASSEGNA', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.MEZZO.CHANGESTATUS', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.MEZZO.DOTAZIONE.EDIT', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.TIPO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.TIPO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.GENERE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.GENERE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.MATRICOLA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.MATRICOLA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.STATI.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.DOTAZIONE.STATI.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.IMPORT.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.IMPORT.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.IMPORT.TIPO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.IMPORT.FILE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.IMPORT.DATA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.IMPORT.UTENTE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.IMPORT.DATAINIZIO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.IMPORT.DATAFINE.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.IMPORT.UPLOAD', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.IMPORT.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PROVINCIA.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PROVINCIA.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PROVINCIA.SIGLA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PROVINCIA.SIGLA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PROVINCIA.DESCRIZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PROVINCIA.DESCRIZIONE.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.PROVINCIA.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.PROVINCIA.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.AREA.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.AREA.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.AREA.PROVINCIA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.AREA.PROVINCIA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.AREA.NOME.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.AREA.NOME.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.AREA.DESCRIZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.AREA.DESCRIZIONE.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.AREA.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.AREA.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.NOME.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.NOME.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.DESCRIZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.DESCRIZIONE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.CENTROCOSTO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.CENTROCOSTO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.AREA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.AREA.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.POSTAZIONE.DOTAZIONI.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.POSTAZIONE.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.POSTAZIONE.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.POSTAZIONE.DOTAZIONE.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.MEZZO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.CARTA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.NUMERO_SCONTRINO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.GESTORE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.DATA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.DISTRIBUTORE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.CHILOMETRAGGIO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.TIPO_CARBURANTE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.QUANTITA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.IMPORTO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.SCONTRINO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.EXTRA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.POSTAZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.RIFORNIMENTO.PINCARD.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.NUMERO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.NUMERO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.MEZZO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.CARTA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.GESTORE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.KMRET.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.KMRET.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.MEZZORET.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.MEZZORET.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.NOTE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.NOTE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.STATI.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SCONTRINO.PINCARD.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.SCONTRINO.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SOCCORSO.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SOCCORSO.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SOCCORSO.MEZZO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SOCCORSO.PERIODO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SOCCORSO.NUMERO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SOCCORSO.MEDIA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.SOCCORSO.RIFORNIMENTI.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.NUMERO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.NUMERO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.IDENTIFICATIVO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.IDENTIFICATIVO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.PIN.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.PIN.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.SCADENZA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.SCADENZA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.GESTORE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.GESTORE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.MEZZO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.MEZZO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.NOTE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.NOTE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.DATAATT.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.RIFORNIMENTI.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CARTA.STATI.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.CARTA.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.CARTA.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.NOME.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.NOME.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.COGNOME.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.COGNOME.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.QUALIFICA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.QUALIFICA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.MATRICOLA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.MATRICOLA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.POSTAZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PERSONA.POSTAZIONE.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.PERSONA.EDIT', 0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.PERSONA.DELETE', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.CODICE.OPERATORE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.CODICE.OPERATORE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.CODICE.BUSTA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.CODICE.BUSTA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.STATO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.GESTORE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.GESTORE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.NOTE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.PINCARD.NOTE.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.PINCARD.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.PINCARD.DELETE',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CODCARB.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CODCARB.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CODCARB.TIPO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CODCARB.TIPO.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CODCARB.VALORE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CODCARB.VALORE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CODCARB.CONSENTITO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CODCARB.CONSENTITO.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.CODCARB.EDIT', 0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSMEZZO.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSMEZZO.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSMEZZO.MEZZO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSMEZZO.POSTAZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSMEZZO.DATAINIZIO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSMEZZO.DATAFINE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSMEZZO.SERBATOIO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ASSMEZZO.CHILOMETRI.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.DESCRIZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.NOTA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.NOTA.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.TIPO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.STATO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.RIFORNIMENTO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.ANOMALIA.GESTORE.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CONSUMI.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CONSUMI.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CONSUMI.MEZZO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CONSUMI.DATA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CONSUMI.RIF.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CONSUMI.QUANTITA.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CONSUMI.CHILOMETRI.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.CONSUMI.CONSUMO.VIEW',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.GENEREASSET.*',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.GENEREASSET.ID.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.GENEREASSET.DESCRIZIONE.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.GENEREASSET.DESCRIZIONE.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.GENEREASSET.TIPO.VIEW',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('MODEL.GENEREASSET.TIPO.EDIT',0);

INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.GENEREASSET.EDIT',0);
INSERT INTO PERMISSIONS(NAME,VERSION) VALUES ('ACTION.GENEREASSET.DELETE',0);

