INSERT INTO USERS (ID, USERNAME, PASSWORD, NAME, SURNAME, ACTIVE, REMOVED, VERSION)
VALUES ( 1,
	'admin', 
	'e5e9fa1ba31ecd1ae84f75caaa474f3a663f05f4', 
	'admin', 
	'admin',
	1,
	0,
	0
	);

INSERT INTO USERS (ID, USERNAME, PASSWORD, NAME, SURNAME, ACTIVE, REMOVED, VERSION)
VALUES ( 2,
	'system', 
	'system', 
	'system', 
	'system',
	0,
	0,
	0
	);
	
INSERT INTO GROUPS (ID, NAME, DESCRIPTION, VERSION)
VALUES (1, 'ADMINISTRATORS', 'Amministratori di sistema', 0);

INSERT INTO USERS_GROUPS ( ID, ID_USERS, ID_GROUPS )
VALUES (1, 1, 1);

INSERT INTO GROUP_PERMISSION ( ID, ID_GROUPS, ID_PERMISSIONS )
VALUES (1, 1, 1);


